# Generated by Django 5.2.6 on 2025-11-14 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('nacionalidad', models.CharField(max_length=50, verbose_name='Nacionalidad')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('fecha_fallecimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de fallecimiento')),
                ('biografia', models.TextField(help_text='Breve biografía del autor', verbose_name='Biografía')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('activo', models.BooleanField(default=True, verbose_name='Autor activo')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('clienteid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('fecharegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('preferenciasgenero', models.TextField(blank=True, verbose_name='Preferencias de Género')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('editorialid', models.AutoField(primary_key=True, serialize=False)),
                ('nombreeditorial', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la Editorial')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('emailcontacto', models.EmailField(max_length=254, verbose_name='Email de Contacto')),
                ('sitioweb', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('paisorigen', models.CharField(max_length=50, verbose_name='País de Origen')),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
                'ordering': ['nombreeditorial'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del libro')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('genero', models.CharField(choices=[('FIC', 'Ficción'), ('ROM', 'Romance'), ('TER', 'Terror'), ('CIE', 'Ciencia Ficción'), ('FAN', 'Fantasía'), ('HIS', 'Histórico'), ('BIO', 'Biografía'), ('INF', 'Infantil')], max_length=3, verbose_name='Género')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de publicación')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Cantidad en stock')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('autores', models.ManyToManyField(related_name='libros', to='app_Libreria.autor', verbose_name='Autores')),
                ('editorial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libros', to='app_Libreria.editorial', verbose_name='Editorial')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Venta')),
                ('cantidad_total', models.PositiveIntegerField(verbose_name='Cantidad Total')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('COM', 'Completada'), ('CAN', 'Cancelada'), ('DEV', 'Devuelta')], default='PEN', max_length=3, verbose_name='Estado')),
                ('cliente_email', models.EmailField(max_length=254, verbose_name='Email del Cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='app_Libreria.cliente', verbose_name='Cliente')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_principal', to='app_Libreria.libro', verbose_name='Libro Principal')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('detalleDeLaVentaid', models.AutoField(primary_key=True, serialize=False)),
                ('precioUnitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('iva', models.DecimalField(decimal_places=2, default=0.16, max_digits=5, verbose_name='IVA')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='app_Libreria.libro', verbose_name='Libro')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app_Libreria.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
                'ordering': ['-venta__fecha_venta'],
            },
        ),
    ]
